  before_script:
    - git checkout $CI_COMMIT_REF_NAME
    - git remote set-url origin "git@gitlab.com:$CI_PROJECT_PATH.git"
    - git pull origin $CI_COMMIT_REF_NAME
    - git fetch --tags
    - npm install
  script:
    - npx release-it --preRelease=alpha --ci -VV
  only:
    refs:
      - alpha
