#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# get the current master, so we can calculate affected correctly
echo "Fetching master form origin in local master."
git fetch origin main:main

master_base="main"
is_libs_changed=false
publishables_libs=("product" "common-ui")
affected_libs=$(npx nx print-affected --type=lib --select=projects --base=$master_base --head=HEAD --plain)

echo $affected_libs

for publishables_lib in ${publishables_libs[@]}
do
  if [[ "$affected_libs" == *"$publishables_lib"* ]]; then
    is_libs_changed=true
  fi
done

echo '$is_libs_changed'
echo $is_libs_changed

if $is_libs_changed; then
  echo -e "gitBranchCurrentName=$(git rev-parse --abbrev-ref HEAD)" > ./versions/branch-name-changed-libs.txt
  git add ./versions/branch-name-changed-libs.txt
  git commit -m "automali"
fi
