#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# get the current master, so we can calculate affected correctly
echo "Fetching master form origin in local master."
git fetch origin main:main

master_base="main"
is_libs_changed=false
publishables_libs=("product" "common-ui")
affected_libs=$(npx nx print-affected --type=lib --select=projects --base=$master_base --plain)
updatedAt=$(date '+%Y-%m-%d %H:%M:%S')
branchName=$(git rev-parse --abbrev-ref HEAD)

echo "affected.libs: $affected_libs"

for publishables_lib in ${publishables_libs[@]}
do
  if [[ "$affected_libs" == *"$publishables_lib"* ]]; then
    is_libs_changed=true
  fi
done

if $is_libs_changed; then
  if bash -c ": >/dev/tty" >/dev/null 2>/dev/null; then
      printf "%b\n" "You have changed libs: $affected_libs. Do you want to publish to npm (yes: 1/no: 0)?"
      exec < /dev/tty
      read confirmed || true
      exec <&-

      if $confirmed; then
        echo -e "branchName=$branchName\nupdatedAt=$updatedAt" > ./versions/info-changed-libs.txt
        git add ./versions/info-changed-libs.txt
      else
        echo "You have not commited info-changed-libs.txt yet"
      fi
  fi
fi
